name: Load Test with Locust

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Locust
        run: pip install locust

      - name: Run Locust load test
        run: |
          locust -f locust.py --headless --users 50 --spawn-rate 5 --host https://jsonplaceholder.typicode.com --run-time 2m --stop-timeout 60
          if [ $? -ne 0 ]; then
            echo "Locust load test failed!"
            exit 1
          fi
