name: Run Load and Spike Tests

on:
  push:
    branches:
      - main

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir beautifulsoup4 locust

      # Run Regular Load Test
      - name: Run Standard Load Test
        run: |
          locust -f locust.py --headless --users 50 --spawn-rate 5 --host https://jsonplaceholder.typicode.com --run-time 2m --stop-timeout 60 --html locust_report.html

      # Run Spike Test
      - name: Run Spike Test
        run: |
          locust -f spike_test.py --headless --users 1000 --spawn-rate 500 --host https://jsonplaceholder.typicode.com --run-time 1m --stop-timeout 60 --html spike_report.html

      - name: Verify Reports
        run: |
          ls -lh
          test -f locust_report.html && echo "✅ Load Test Report Exists"
          test -f spike_report.html && echo "✅ Spike Test Report Exists"

      - name: Upload Load Test Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-load-report
          path: locust_report.html

      - name: Upload Spike Test Report
        uses: actions/upload-artifact@v4
        with:
          name: spike-test-report
          path: spike_report.html

#      - name: Install git-comment
#        run: |
#          curl -s https://api.github.com/repos/git-comment/git-comment/releases/latest \
#          | grep "browser_download_url.*linux_amd64" \
#          | cut -d : -f 2,3 \
#          | tr -d \" \
#          | wget -qi -
#          chmod +x git-comment_*.tar.gz
#          tar -xvzf git-comment_*.tar.gz
#          sudo mv git-comment /usr/local/bin

#      - name: Comment on commit with git-comment
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git-comment \
#            --repo ${{ github.repository }} \
#            --commit ${{ github.sha }} \
#            --message "✅ **Locust Load & Spike Tests Completed**
#            📄 [Standard Load Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
#            📈 [Spike Load Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
#            _Triggered by commit \`${{ github.sha }}\`_" \
#            --author "GitHub Actions Bot" \
#            --token $GITHUB_TOKEN
