name: Run Load Test

on:
  push:
    branches:
      - main

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install beautifulsoup4 locust

      # Step 4: Run the load test with locust
      - name: Run Load Test
        run: |
          locust -f locust.py --headless --users 50 --spawn-rate 5 --host https://jsonplaceholder.typicode.com --run-time 2m --stop-timeout 60

      # Step 5: Run custom HTML report script
      - name: Run custom report script
        run: |
          python custom-report.py
